// user-avatar/userav136.webp

export const users = [
  {
    createdAt: "2021-08-04T17:38:45Z",
    first_name: "Norene",
    last_name: "Theobald",
    user_name: "ntheobald0",
    email: "ntheobald0@behance.net",
    password: "lY4a{&Ew",
    avatar: "user-avatar/userav136.webp",
    gender: "Female",
    role: "IT Support Specialist",
    department: "Services",
    phone: "109-687-3838",
    address: "2 Macpherson Trail",
    city: "Helsingborg",
    state: "Skåne",
    country: "Sweden",
    zipCode: "252 20",
    type: "EMPLOYEE",
  },
  {
    createdAt: "2023-06-18T03:52:39Z",
    first_name: "Nealon",
    last_name: "Jinkin",
    user_name: "njinkin1",
    email: "njinkin1@nasa.gov",
    password: "cQ10o_jIAyXmo",
    avatar: "user-avatar/userav035.webp",
    gender: "Male",
    role: "Software Engineer",
    department: "Legal",
    phone: "469-265-9917",
    address: "5538 Muir Plaza",
    city: "Södertälje",
    state: "Stockholm",
    country: "Sweden",
    zipCode: "151 22",
    type: "CLIENT",
  },
  {
    createdAt: "2020-08-04T05:29:17Z",
    first_name: "Maurise",
    last_name: "Woodeson",
    user_name: "mwoodeson2",
    email: "mwoodeson2@netlog.com",
    password: "qF5lmf~UWHK8",
    avatar: "user-avatar/userav237.webp",
    gender: "Male",
    role: "IT Support Specialist",
    department: "Business Development",
    phone: "434-629-3041",
    address: "2 American Ash Trail",
    city: "Stockholm",
    state: "Stockholm",
    country: "Sweden",
    zipCode: "101 22",
    type: "CLIENT",
  },
  {
    createdAt: "2022-01-08T23:32:04Z",
    first_name: "Eirena",
    last_name: "Caile",
    user_name: "ecaile3",
    email: "ecaile3@weibo.com",
    password: "xU7IpRysqG+yyl",
    avatar: "user-avatar/userav338.webp",
    gender: "Female",
    role: "Project Manager",
    department: "Research and Development",
    phone: "509-713-3505",
    address: "66 Spaight Hill",
    city: "Varberg",
    state: "Halland",
    country: "Sweden",
    zipCode: "432 30",
    type: "EMPLOYEE",
  },
  {
    createdAt: "2018-03-02T21:21:46Z",
    first_name: "Kipper",
    last_name: "Kemsley",
    user_name: "kkemsley4",
    email: "kkemsley4@scientificamerican.com",
    password: "jB0G3}SVeOEELu",
    avatar: "user-avatar/userav439.webp",
    gender: "Male",
    role: "Sales Associate",
    department: "Marketing",
    phone: "155-253-2420",
    address: "83060 Mifflin Junction",
    city: "Kungsör",
    state: "Västmanland",
    country: "Sweden",
    zipCode: "736 34",
    type: "EMPLOYEE",
  },
  {
    createdAt: "2019-06-20T21:41:58Z",
    first_name: "Ulrikaumeko",
    last_name: "Collopy",
    user_name: "ucollopy5",
    email: "ucollopy5@nps.gov",
    password: "eR0$X|Ik",
    avatar: "user-avatar/userav540.webp",
    gender: "Female",
    role: "Executive Assistant",
    department: "Marketing",
    phone: "539-779-7766",
    address: "5221 Spenser Center",
    city: "Vårgårda",
    state: "Västra Götaland",
    country: "Sweden",
    zipCode: "447 82",
    type: "EMPLOYEE",
  },
  {
    createdAt: "2018-04-08T16:32:38Z",
    first_name: "Charisse",
    last_name: "Birdwhistle",
    user_name: "cbirdwhistle6",
    email: "cbirdwhistle6@dailymotion.com",
    password: "aM0.)g+yL",
    avatar: "user-avatar/userav641.webp",
    gender: "Non-binary",
    role: "Software Engineer",
    department: "Legal",
    phone: "691-417-8935",
    address: "2931 Moulton Terrace",
    city: "Örebro",
    state: "Örebro",
    country: "Sweden",
    zipCode: "702 21",
    type: "CLIENT",
  },
  {
    createdAt: "2023-08-23T03:55:35Z",
    first_name: "Ugo",
    last_name: "Steade",
    user_name: "usteade7",
    email: "usteade7@nsw.gov.au",
    password: "oQ2s)9us",
    avatar: "user-avatar/userav742.webp",
    gender: "Male",
    role: "IT Support Specialist",
    department: "Product Management",
    phone: "139-992-8418",
    address: "50 Dorton Alley",
    city: "Katrineholm",
    state: "Södermanland",
    country: "Sweden",
    zipCode: "641 96",
    type: "CLIENT",
  },
  {
    createdAt: "2019-08-25T06:03:36Z",
    first_name: "Vinny",
    last_name: "Dobbinson",
    user_name: "vdobbinson8",
    email: "vdobbinson8@uol.com.br",
    password: "eI03qSXuG=}7`P6",
    avatar: "user-avatar/userav843.webp",
    gender: "Male",
    role: "IT Support Specialist",
    department: "Accounting",
    phone: "478-364-9224",
    address: "6657 Corben Pass",
    city: "Alunda",
    state: "Uppsala",
    country: "Sweden",
    zipCode: "747 30",
    type: "CLIENT",
  },
  {
    createdAt: "2018-07-21T07:04:28Z",
    first_name: "Rorie",
    last_name: "Woodyear",
    user_name: "rwoodyear9",
    email: "rwoodyear9@theglobeandmail.com",
    password: "zM4CzwIQxk0`mA9k",
    avatar: "user-avatar/userav944.webp",
    gender: "Female",
    role: "IT Support Specialist",
    department: "Marketing",
    phone: "116-638-4427",
    address: "499 Maple Point",
    city: "Huddinge",
    state: "Stockholm",
    country: "Sweden",
    zipCode: "141 05",
    type: "EMPLOYEE",
  },
  {
    createdAt: "2021-09-06T03:38:00Z",
    first_name: "Aldric",
    last_name: "Denes",
    user_name: "adenesa",
    email: "adenesa@dion.ne.jp",
    password: "uO5amdSW{+e&,4",
    avatar: "user-avatar/userav1045.webp",
    gender: "Male",
    role: "IT Support Specialist",
    department: "Training",
    phone: "703-948-2315",
    address: "5599 Redwing Point",
    city: "Härnösand",
    state: "Västernorrland",
    country: "Sweden",
    zipCode: "871 60",
    type: "EMPLOYEE",
  },
  {
    createdAt: "2021-11-28T12:34:41Z",
    first_name: "Sisile",
    last_name: "Dillingston",
    user_name: "sdillingstonb",
    email: "sdillingstonb@last.fm",
    password: "jV2YdW3R?NQ3",
    avatar: "user-avatar/userav1146.webp",
    gender: "Female",
    role: "Software Engineer",
    department: "Research and Development",
    phone: "176-112-3611",
    address: "53630 Anzinger Trail",
    city: "Borås",
    state: "Västra Götaland",
    country: "Sweden",
    zipCode: "504 37",
    type: "EMPLOYEE",
  },
  {
    createdAt: "2021-01-06T06:47:08Z",
    first_name: "Vikky",
    last_name: "Bwy",
    user_name: "vbwyc",
    email: "vbwyc@digg.com",
    password: "jV2YdW3R?NQ3",
    avatar: "user-avatar/userav1247.webp",
    gender: "Female",
    role: "IT Support Specialist",
    department: "Support",
    phone: "224-787-0336",
    address: "0 Prentice Circle",
    city: "Ånge",
    state: "Västernorrland",
    country: "Sweden",
    zipCode: "841 23",
    type: "EMPLOYEE",
  },
  {
    createdAt: "2022-08-14T08:59:03Z",
    first_name: "Mab",
    last_name: "Ryland",
    user_name: "mrylandd",
    email: "mrylandd@spiegel.de",
    password: "dF8pvM(vy$A&pu",
    avatar: "user-avatar/userav1348.webp",
    gender: "Female",
    role: "Sales Associate",
    department: "Business Development",
    phone: "255-608-6974",
    address: "1 Grover Crossing",
    city: "Värnamo",
    state: "Jönköping",
    country: "Sweden",
    zipCode: "331 29",
    type: "EMPLOYEE",
  },
];
