import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";

const monaSans = localFont({ src: "./_assets/fonts/Mona-Sans.woff2" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={monaSans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
